const nomes= [
  "Ana", "João", "Maria", "Pedro", "Lucas", "Mariana", "Gabriel", "Rafael",
  "Bruna", "Felipe", "Camila", "Diego", "Amanda", "Matheus", "Juliana",
  "Thiago", "Larissa", "Renato", "Beatriz", "Rodrigo", "Paula", "Eduardo",
  "Natália", "Victor", "Carolina", "André", "Letícia", "Daniel", "Aline",
  "Gustavo", "Fernanda", "Caio", "Patrícia", "Bruno", "Isabela", "Alexandre",
  "Vanessa", "Igor", "Tatiane", "Henrique", "Priscila", "Leonardo", "Sabrina",
  "Marcelo", "Cristiane", "Fábio", "Elaine", "Vitor", "Simone", "Jorge",
  "Cláudia", "Samuel", "Débora", "Ricardo", "Michele", "Wesley", "Rita",
  "Leandro", "Márcia", "Roberto", "Jéssica", "Vinícius", "Kelly", "Fernando",
  "Luciana", "Otávio", "Monique", "César", "Bianca", "Douglas", "Renata",
  "Alan", "Tainá", "Jefferson", "Flávia", "Elias", "Nayara", "Murilo",
  "Cintia", "Ronaldo", "Milena", "Hugo", "Rayssa", "Arthur", "Lorena"
];

let falas = ["Vai corinthians!","é o que sobra?","Nem fudendo","alfa aqui tá?","beta!","jonas mo gay","ala teu pai",
    "O que preferes?","mano tipo","Tipo bixo mesmo","oq tu acha?","antes de ir comer","Tranquilo","mo pas","n word","twiteiro medio","...",
    "LADRÂO!","Ai, que delicia","Tu que é","tu que deixa","comeu miojo?","passa pano!","Odeio os verdes","Odeio os roxos",
    "odeio os rosa","odeio os laranja","Seu bobão molhado",
  "Seu banana gigante",
  "Tolo sem noção",
  "Cabeça de vento",
  "Paspalho de marca",
  "Bobalhão sem rumo",
  "Zé ruela cansado",
  "Palhaço de aluguel",
  "Banana ambulante",
  "Troço sem graça",
  "Mala sem alça",
  "Panaca de plantão",
  "Chato pra caramba",
  "Nó cego chato",
  "Besta quadrada",
  "Tranqueira sem futuro",
  "Orelhudo de festa",
  "Zé ninguém molhado",
  "Cabeça de bagre",
  "Mané de novela",
  "Baranga de luxo",
  "Lesado de carteirinha",
  "Desenxabido sem classe",
  "Pateta de esquina",
  "Trombadinha de espuma",
  "Bobalhão de sempre",
  "Fiasco ambulante",
  "Nababão sem limites",
  "Aberração de bolso",
  "Enjoado de fábrica",
   "Gênio das galáxias",
  "Lenda do caos",
  "Brabo sem limites",
  "Mito dos cafés",
  "Fera dos cliques",
  "Astro das tretas",
  "Craque do improviso",
  "Prodígio das piadas",
  "Monstro do código",
  "Sábio das ruas",
  "Rei das gambis",
  "Lord dos memes",
  "Patrão da zoeira",
  "Chefe das lendas",
  "Majestade dos bugs",
   "Titã das galáxias",
  "Deus das planilhas",
  "Messias dos memes",
  "Imperador do caos",
  "Dragão do carisma",
  "Sabidão supremo intergaláctico",
  "Monarca das tretas",
  "Oráculo das piadas",
  "Faraó do estilo",
  "Colosso do talento",
  "Demônio do charme",
  "Gigante da sabedoria",
  "Divindade do hype",
  "Apocalipse do swag",
  "Rei do impossível",
    "Oi, bonitinho",
  "E aí, encanto",
  "Você brilha",
  "Oi, charme",
  "Fala, estrela",
  "Oi, lindinha",
  "Cheguei, sumido",
  "Você encanta",
  "Oi, beleza",
  "Sua presença ilumina",
  "Hey, fofura",
  "Você é charme",
  "Oi, crush",
  "Me notou?",
  "Gosto de você",
   "E aí, charme",
  "Oi, doce",
  "Você fascina",
  "Olá, sorriso",
  "E aí, paixão",
  "Oi, irresistível",
  "Você hipnotiza",
  "Olá, fofinho",
  "Hey, gracinha",
  "Que saudade",
  "Você encanta mesmo",
  "Oi, perfeição",
  "Chega mais",
  "Oi, preciosidade",
  "Tudo bem, lindo?",
  "jesus",
  "grosso",
  "feito",
  "bao?",
  "goku > ronaldo"
]