const nomes= [
  "Ana", "João", "Maria", "Pedro", "Lucas", "Mariana", "Gabriel", "Rafael",
  "Bruna", "Felipe", "Camila", "Diego", "Amanda", "Matheus", "Juliana",
  "Thiago", "Larissa", "Renato", "Beatriz", "Rodrigo", "Paula", "Eduardo",
  "Natália", "Victor", "Carolina", "André", "Letícia", "Daniel", "Aline",
  "Gustavo", "Fernanda", "Caio", "Patrícia", "Bruno", "Isabela", "Alexandre",
  "Vanessa", "Igor", "Tatiane", "Henrique", "Priscila", "Leonardo", "Sabrina",
  "Marcelo", "Cristiane", "Fábio", "Elaine", "Vitor", "Simone", "Jorge",
  "Cláudia", "Samuel", "Débora", "Ricardo", "Michele", "Wesley", "Rita",
  "Leandro", "Márcia", "Roberto", "Jéssica", "Vinícius", "Kelly", "Fernando",
  "Luciana", "Otávio", "Monique", "César", "Bianca", "Douglas", "Renata",
  "Alan", "Tainá", "Jefferson", "Flávia", "Elias", "Nayara", "Murilo",
  "Cintia", "Ronaldo", "Milena", "Hugo", "Rayssa", "Arthur", "Lorena",
  "Pablo", "Ariadne", "Brenda", "Cauã", "Giovanna", "Davi", "Sofia",
  "Yasmin", "Enzo", "Lara", "Heitor", "Isadora", "Samuel", "Vitória",
  "Cecília", "Guilherme", "Emanuel", "Alícia", "Noah", "Evelyn",
  "Luan", "Maya", "Cauã", "Esther", "Ian", "Lívia", "Levi", "Helena",
  "Túlio", "Olívia", "Caetano", "Júlia",
  "Gael", "Marina", "Benjamin", "Lorena", "Dante", "Clara",
  "Lorenzo", "Isabel", "Theo", "Ana Clara",
  "Samuel", "Manuela", "Vicente", "Yara",
  "Cauã", "Eloá", "Enrico", "Luna",
  "Lucca", "Catarina", "Rafael", "Estela","Betito","Critina","Snopdog","Thiago","Eduardo",
  "Bruna","Marcos","Samantha","Julio","Cintia","Fernando","Larissa","Gustavo","Amanda",
  "Roberta","Vinicius","Patricia","Diego","Camila","Alexandre","Isabela","Rafael","Bianca","Carlos"
];

let falas = [
  "Olá!", "Como vai?", "Que dia lindo!", "Estou com fome.", "Vamos brincar?",
  "Adoro aventuras!", "Você é meu amigo?", "Vamos explorar juntos!",
  "Cuidado por onde anda!", "Que lugar interessante!", "Vamos correr!",
  "Estou cansado.", "Vamos descansar um pouco?", "Que cheiro é esse?",
  "Ouvi algo estranho.", "Vamos nadar!", "Adoro o sol!", "Vamos subir aquela colina?",
  "Olha aquele pássaro!", "Vamos fazer", "uma fogueira!", "Estou com sede.",
  "Vamos procurar comida!", "Que tal uma corrida?", "Estou feliz hoje!",
  "Vamos cantar uma música!", "Adoro flores!", "Vamos colher frutas!",
  "Que tal uma caça ao tesouro?", "Estou com frio.", "Vamos construir um abrigo!",
  "Que tal uma festa?", "Vamos dançar!", "Estou com sono.", "Vamos olhar as estrelas!",
  "Que tal um piquenique?", "Vamos fazer novos amigos!", "Estou animado!",
  "Vamos explorar a floresta!", "Que tal um passeio?", "Vamos nadar no lago!",
  "Estou curioso.", "Vamos descobrir algo novo!", "Que tal uma aventura noturna?",
  "Vamos observar os animais!", "Estou com medo.", "Vamos ficar juntos!",
  "Que tal uma história?", "Vamos desenhar!", "Estou empolgado!", "Vamos jogar um jogo!",
  "Que tal uma caminhada?", "Vamos fazer uma surpresa!", "Estou grato por você!",
  "Vamos ajudar alguém!", "Que tal um desafio?", "Vamos aprender algo novo!",
  "Estou orgulhoso de nós!", "Vamos celebrar!", "Que tal um descanso?", "Vamos sonhar grande!",
  "Estou feliz por estar aqui!", "Vamos fazer memórias!", "Que tal um abraço?", "Vamos ser felizes!",
  "Estou contente!", "Vamos aproveitar o dia!", "Que tal um sorriso?", "Vamos ser gentis!",
  "Estou esperançoso!", "Vamos fazer o bem!", "Que tal uma aventura juntos?", "Vamos ser incríveis!",

]